markdown: maruku
pygments: false

permalink: /:categories/:title/
baseurl: /LaTeX

title: "LaTeX course"
subtitle: "University of Amsterdam"

weeks:
  week1: Week 1
  week2: Week 2
  week3: Week 3
  week4: Week 4
