markdown: maruku
pygments: true

permalink: /:categories/:title/
baseurl: /LaTeX

title: "LaTeXcursus"
subtitle: "UvA Bachelor Wiskunde 2016"

weeks:
  week1: Week 1
  week2: Week 2
  week3: Week 3
  week4: Week 4
